(function (root) {
  'use strict';
  const Core=root.PhonoLayerLearningCore, Retrieval=root.PhonoLayerRetrievalCore;
  if(!Core)throw new Error('learning-db-core.js 未加载'); if(!Retrieval)throw new Error('retrieval-core.js 未加载');
  // Historical IndexedDB name is intentionally retained so v0.8.10 upgrades in place.
  const DB_NAME='shengjian-phonolayer-learning-v07-experimental';
  const DB_VERSION=3;
  const ENTRY_STORE='entries', OBS_STORE='observations', META_STORE='meta', RETRIEVAL_SESSION_STORE='retrievalSessions', RETRIEVAL_EVENT_STORE='retrievalEvents', ANNOTATION_EVENT_STORE='annotationEvents';
  function req(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB request failed'));});}
  function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('IndexedDB transaction failed'));tx.onabort=()=>reject(tx.error||new Error('IndexedDB transaction aborted'));});}
  function ensureStore(db,name,options,indexes=[]){if(db.objectStoreNames.contains(name))return;const store=db.createObjectStore(name,options);for(const [n,k,o] of indexes)store.createIndex(n,k,o||{unique:false});}
  async function open(){if(!('indexedDB'in root))throw new Error('当前浏览器不支持 IndexedDB');return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;ensureStore(db,ENTRY_STORE,{keyPath:'key'},[['language','language'],['base','base'],['updatedAt','updatedAt']]);ensureStore(db,OBS_STORE,{keyPath:'id'},[['entryKey','entryKey'],['documentId','documentId'],['language','language'],['updatedAt','updatedAt']]);ensureStore(db,META_STORE,{keyPath:'key'});ensureStore(db,RETRIEVAL_SESSION_STORE,{keyPath:'id'},[['documentId','documentId'],['language','language'],['startedAt','startedAt'],['endedAt','endedAt']]);ensureStore(db,RETRIEVAL_EVENT_STORE,{keyPath:'id'},[['sessionId','sessionId'],['documentId','documentId'],['annotationId','annotationId'],['entryKey','entryKey'],['ratedAt','ratedAt']]);ensureStore(db,ANNOTATION_EVENT_STORE,{keyPath:'id'},[['documentId','documentId'],['annotationId','annotationId'],['at','at'],['kind','kind']]);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('无法打开个人积累数据库'));});}
  async function addAnnotationEvent(store, event){ store.add(Core.makeAnnotationEvent(event, event.at||Date.now())); }
  async function upsertObservation(record){const db=await open(),now=Date.now();const entry=Core.makeEntry(record,now),observation=Core.makeObservation(record,now);const tx=db.transaction([ENTRY_STORE,OBS_STORE,ANNOTATION_EVENT_STORE],'readwrite');const entries=tx.objectStore(ENTRY_STORE),observations=tx.objectStore(OBS_STORE),events=tx.objectStore(ANNOTATION_EVENT_STORE);const previous=await req(observations.get(observation.id));const oldEntryKey=previous?.entryKey||null;const existingEntry=await req(entries.get(entry.key));if(existingEntry)entry.createdAt=existingEntry.createdAt||entry.createdAt;if(previous){observation.observedAt=previous.observedAt||observation.observedAt;observation.projectionRevision=Math.max(1,Number(previous.projectionRevision)||1)+1;}entries.put(entry);observations.put(observation);events.add(Core.makeAnnotationEvent({kind:previous?'updated':'created',documentId:observation.documentId,documentTitle:observation.documentTitle,annotationId:observation.annotationId,at:now,before:previous||null,after:observation},now));await txDone(tx);db.close();if(oldEntryKey&&oldEntryKey!==entry.key)await pruneEntryIfOrphan(oldEntryKey);return{entry,observation};}
  async function removeObservation(documentId,annotationId){const db=await open(),now=Date.now();const id=Core.makeObservationId(documentId,annotationId);const tx=db.transaction([OBS_STORE,ANNOTATION_EVENT_STORE],'readwrite');const store=tx.objectStore(OBS_STORE);const previous=await req(store.get(id));if(previous){store.delete(id);tx.objectStore(ANNOTATION_EVENT_STORE).add(Core.makeAnnotationEvent({kind:'removed',documentId:previous.documentId,documentTitle:previous.documentTitle,annotationId:previous.annotationId,at:now,before:previous,after:null},now));}await txDone(tx);db.close();if(previous?.entryKey)await pruneEntryIfOrphan(previous.entryKey);}
  async function pruneEntryIfOrphan(entryKey){const db=await open();const tx=db.transaction([ENTRY_STORE,OBS_STORE],'readwrite');const matches=await req(tx.objectStore(OBS_STORE).index('entryKey').getAll(entryKey));if(!matches.length)tx.objectStore(ENTRY_STORE).delete(entryKey);await txDone(tx);db.close();}
  async function startRetrievalSession(record){const db=await open();const session=Retrieval.makeSession(record,Date.now());const tx=db.transaction(RETRIEVAL_SESSION_STORE,'readwrite');tx.objectStore(RETRIEVAL_SESSION_STORE).put(session);await txDone(tx);db.close();return session;}
  async function recordRetrievalEvent(record){const db=await open();const event=Retrieval.makeEvent(record,Date.now());const tx=db.transaction(RETRIEVAL_EVENT_STORE,'readwrite');tx.objectStore(RETRIEVAL_EVENT_STORE).add(event);await txDone(tx);db.close();return event;}
  async function finishRetrievalSession(sessionId,patch={}){const db=await open();const tx=db.transaction(RETRIEVAL_SESSION_STORE,'readwrite');const store=tx.objectStore(RETRIEVAL_SESSION_STORE);const current=await req(store.get(String(sessionId||'').trim()));if(!current){tx.abort();db.close();throw new Error('检索练习 session 不存在');}const merged=Retrieval.makeSession({...current,...patch,id:current.id,endedAt:patch.endedAt||Date.now()},Date.now());store.put(merged);await txDone(tx);db.close();return merged;}
  async function listRetrievalEvents(sessionId=''){const db=await open();const tx=db.transaction(RETRIEVAL_EVENT_STORE,'readonly');const store=tx.objectStore(RETRIEVAL_EVENT_STORE);const rows=sessionId?await req(store.index('sessionId').getAll(String(sessionId))):await req(store.getAll());await txDone(tx);db.close();rows.sort((a,b)=>(a.ratedAt||0)-(b.ratedAt||0)||(a.sequence||0)-(b.sequence||0));return rows;}
  async function getSnapshot(){const db=await open();const names=[ENTRY_STORE,OBS_STORE,META_STORE,RETRIEVAL_SESSION_STORE,RETRIEVAL_EVENT_STORE,ANNOTATION_EVENT_STORE];const tx=db.transaction(names,'readonly');const [entries,observations,meta,retrievalSessions,retrievalEvents,annotationEvents]=await Promise.all(names.map(n=>req(tx.objectStore(n).getAll())));await txDone(tx);db.close();return{entries,observations,meta,retrievalSessions,retrievalEvents,annotationEvents};}
  async function getRetrievalStats(){const snap=await getSnapshot();const completedSessions=(snap.retrievalSessions||[]).filter(x=>x.endedAt).length;return{sessions:completedSessions,events:(snap.retrievalEvents||[]).length,summary:Retrieval.summarizeEvents(snap.retrievalEvents||[])};}
  async function listSummary(language=''){const snap=await getSnapshot();let rows=Core.summarize(snap.entries,snap.observations);if(language)rows=rows.filter(x=>x.language===language);rows.sort((a,b)=>(b.lastSeenAt||b.updatedAt||0)-(a.lastSeenAt||a.updatedAt||0));return rows;}
  function semantic(record){return Core.stableRecord(record||{});}
  function byId(rows,key='id'){return new Map((rows||[]).map(x=>[x?.[key],x]).filter(x=>x[0]));}
  async function importSnapshot(snapshot,mode='merge'){
    const incoming={entries:(snapshot.entries||[]).map(x=>Core.makeEntry(x,x.updatedAt||Date.now())),observations:(snapshot.observations||[]).map(x=>Core.makeObservation(x,x.observedAt||Date.now())),retrievalSessions:(snapshot.retrievalSessions||[]).map(x=>Retrieval.makeSession(x,x.startedAt||Date.now())),retrievalEvents:(snapshot.retrievalEvents||[]).map(x=>Retrieval.makeEvent(x,x.ratedAt||Date.now())),annotationEvents:(snapshot.annotationEvents||[]).map(x=>Core.makeAnnotationEvent(x,x.at||Date.now())),meta:(snapshot.meta||[]).filter(x=>x?.key)};
    const report={mode,entries:0,observations:0,sessions:0,retrievalEvents:0,annotationEvents:0,duplicates:0,projectionConflicts:0};
    let current={entries:[],observations:[],retrievalSessions:[],retrievalEvents:[],annotationEvents:[],meta:[]}; if(mode!=='replace')current=await getSnapshot();
    if(mode!=='replace'){
      for(const [label,rowsA,rowsB] of [['retrieval event',current.retrievalEvents,incoming.retrievalEvents],['annotation event',current.annotationEvents,incoming.annotationEvents]]){const m=byId(rowsA);for(const row of rowsB){const old=m.get(row.id);if(Core.appendOnlyConflict(old,row))throw new Error(`${label} ID 冲突且内容不同：${row.id}。为保护 append-only 历史，本次导入已中止。`);}}
    }
    const db=await open();const stores=[ENTRY_STORE,OBS_STORE,META_STORE,RETRIEVAL_SESSION_STORE,RETRIEVAL_EVENT_STORE,ANNOTATION_EVENT_STORE];if(mode==='replace'){const clearTx=db.transaction(stores,'readwrite');for(const n of stores)clearTx.objectStore(n).clear();await txDone(clearTx);}
    const tx=db.transaction(stores,'readwrite');
    const curEntries=byId(current.entries,'key'),curObs=byId(current.observations),curSessions=byId(current.retrievalSessions),curRE=byId(current.retrievalEvents),curAE=byId(current.annotationEvents),curMeta=byId(current.meta,'key');
    for(const item of incoming.entries){const old=curEntries.get(item.key);const merged=old?{...old,...item,createdAt:Math.min(Number(old.createdAt)||Infinity,Number(item.createdAt)||Infinity),updatedAt:Math.max(Number(old.updatedAt)||0,Number(item.updatedAt)||0),extensions:{...(old.extensions||{}),...(item.extensions||{})}}:item;tx.objectStore(ENTRY_STORE).put(merged);report.entries++;}
    for(const item of incoming.observations){const old=curObs.get(item.id);const choice=Core.chooseProjection(old,item);const chosen=choice.record;if(choice.conflict)report.projectionConflicts++;tx.objectStore(OBS_STORE).put(chosen);report.observations++;}
    for(const item of incoming.retrievalSessions){const old=curSessions.get(item.id);const chosen=!old?item:((Number(item.endedAt)||Number(item.startedAt)||0)>(Number(old.endedAt)||Number(old.startedAt)||0)?item:old);tx.objectStore(RETRIEVAL_SESSION_STORE).put(chosen);report.sessions++;}
    for(const item of incoming.retrievalEvents){if(curRE.has(item.id)){report.duplicates++;continue;}tx.objectStore(RETRIEVAL_EVENT_STORE).add(item);report.retrievalEvents++;}
    for(const item of incoming.annotationEvents){if(curAE.has(item.id)){report.duplicates++;continue;}tx.objectStore(ANNOTATION_EVENT_STORE).add(item);report.annotationEvents++;}
    for(const item of incoming.meta){if(!curMeta.has(item.key))tx.objectStore(META_STORE).put(item);}
    tx.objectStore(META_STORE).put({key:'lastImportAt',value:new Date().toISOString()});tx.objectStore(META_STORE).put({key:'phonodbSemanticSchema',value:'0.9.0'});await txDone(tx);db.close();return report;
  }
  async function clearAll(){const db=await open();const stores=[ENTRY_STORE,OBS_STORE,META_STORE,RETRIEVAL_SESSION_STORE,RETRIEVAL_EVENT_STORE,ANNOTATION_EVENT_STORE];const tx=db.transaction(stores,'readwrite');for(const n of stores)tx.objectStore(n).clear();await txDone(tx);db.close();}
  root.PhonoLayerLearningDB={DB_NAME,DB_VERSION,open,upsertObservation,removeObservation,getSnapshot,listSummary,importSnapshot,clearAll,startRetrievalSession,recordRetrievalEvent,finishRetrievalSession,listRetrievalEvents,getRetrievalStats};
})(typeof globalThis!=='undefined'?globalThis:this);
