(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.PhonoLayerMemoryCore = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  function norm(value){return String(value??'').normalize('NFC').trim().replace(/\s+/g,' ');}
  function graphemes(text){const s=norm(text);if(!s)return[];if(typeof Intl!=='undefined'&&Intl.Segmenter){const seg=new Intl.Segmenter(undefined,{granularity:'grapheme'});return[...seg.segment(s)].map(x=>x.segment);}return Array.from(s);}
  function emptyRatings(){return{again:0,hard:0,good:0,easy:0,unrated:0,skipped:0};}
  function normalizeRating(value){return['again','hard','good','easy','unrated','skipped'].includes(value)?value:'unrated';}
  function pitchVariant(record={}){const pitch=norm(record.pitch);if(!pitch)return null;return{pitch,pitchSystem:norm(record.pitchSystem),jaPitchModel:norm(record.jaPitchModel),jaPitchDialect:norm(record.jaPitchDialect),jaPitchRepresentation:norm(record.jaPitchRepresentation),jaMorae:norm(record.jaMorae),jaAccentNucleus:norm(record.jaAccentNucleus),jaManualHl:norm(record.jaManualHl),jaPitchSource:norm(record.jaPitchSource)};}
  function pitchKey(record={}){const v=pitchVariant(record);return v?JSON.stringify(v):'';}
  function addPitch(item, record, minimumOne=false){const key=pitchKey(record);if(!key)return;const variant=pitchVariant(record);const old=item.pitches.get(key);const next=minimumOne?Math.max(old?.count||0,1):(old?.count||0)+1;item.pitches.set(key,{...variant,count:next});}
  function ensureRecord(map,seed={}){const key=norm(seed.key||seed.entryKey);if(!key)return null;if(!map.has(key))map.set(key,{key,language:norm(seed.language),base:norm(seed.base),reading:norm(seed.reading),createdAt:Number(seed.createdAt)||0,updatedAt:Number(seed.updatedAt)||0,observationCount:0,retrievalCount:0,afterRecallCount:0,directRevealCount:0,skippedCount:0,lastSeenAt:0,lastReviewedAt:0,documents:new Map(),pitches:new Map(),notes:new Map(),sources:new Set(),readingRatings:emptyRatings(),pitchRatings:emptyRatings(),historicalOnly:true});const item=map.get(key);if(!item.language&&seed.language)item.language=norm(seed.language);if(!item.base&&seed.base)item.base=norm(seed.base);if(!item.reading&&seed.reading)item.reading=norm(seed.reading);if(seed.createdAt)item.createdAt=item.createdAt?Math.min(item.createdAt,Number(seed.createdAt)):Number(seed.createdAt);if(seed.updatedAt)item.updatedAt=Math.max(item.updatedAt,Number(seed.updatedAt));return item;}
  function aggregate(snapshot={}){const map=new Map();for(const entry of snapshot.entries||[])ensureRecord(map,entry);for(const obs of snapshot.observations||[]){const item=ensureRecord(map,obs);if(!item)continue;item.historicalOnly=false;item.observationCount+=1;item.lastSeenAt=Math.max(item.lastSeenAt,Number(obs.updatedAt||obs.observedAt||0));item.updatedAt=Math.max(item.updatedAt,Number(obs.updatedAt||obs.observedAt||0));item.sources.add(norm(obs.source)||'manual');const docId=norm(obs.documentId);if(docId)item.documents.set(docId,norm(obs.documentTitle)||docId);addPitch(item,obs,false);const note=norm(obs.note);if(note)item.notes.set(note,(item.notes.get(note)||0)+1);}for(const event of snapshot.retrievalEvents||[]){if(!norm(event.entryKey))continue;const item=ensureRecord(map,{key:event.entryKey,language:event.language,base:event.base,reading:event.reading,updatedAt:event.ratedAt});if(!item)continue;item.retrievalCount+=1;item.lastReviewedAt=Math.max(item.lastReviewedAt,Number(event.ratedAt||event.revealedAt||event.shownAt||0));if(event.revealMode==='after-recall')item.afterRecallCount+=1;if(event.revealMode==='direct')item.directRevealCount+=1;if(event.skipped||event.readingRating==='skipped')item.skippedCount+=1;item.readingRatings[normalizeRating(event.readingRating)]+=1;item.pitchRatings[normalizeRating(event.pitchRating)]+=1;addPitch(item,event,true);}return[...map.values()].map(item=>({...item,documents:[...item.documents.entries()].map(([id,title])=>({id,title})),pitchVariants:[...item.pitches.values()].sort((a,b)=>b.count-a.count||a.pitch.localeCompare(b.pitch)),notes:[...item.notes.entries()].map(([note,count])=>({note,count})).sort((a,b)=>b.count-a.count||a.note.localeCompare(b.note)),sources:[...item.sources],lastActivityAt:Math.max(item.lastSeenAt,item.lastReviewedAt,item.updatedAt,item.createdAt)})).sort((a,b)=>b.lastActivityAt-a.lastActivityAt||a.base.localeCompare(b.base)||a.reading.localeCompare(b.reading));}
  function pitchLabel(v={}){if(v.pitchSystem==='ja-tokyo'&&v.jaPitchModel){const mora=v.jaMorae?` ${v.jaMorae}`:'';const accent=v.jaPitchRepresentation==='accent-nucleus'?`核${v.jaAccentNucleus||'0'}`:(v.jaManualHl||'manual H/L');return`${accent}${mora} · ${v.pitch}`;}return v.pitch||'';}
  function search(records,query='',language=''){const q=norm(query).toLocaleLowerCase();return(records||[]).filter(row=>{if(language&&row.language!==language)return false;if(!q)return true;const hay=[row.base,row.reading,...(row.pitchVariants||[]).flatMap(x=>[x.pitch,pitchLabel(x),x.jaMorae,x.jaAccentNucleus]),...(row.notes||[]).map(x=>x.note),...(row.documents||[]).map(x=>x.title)].join(' ').toLocaleLowerCase();return hay.includes(q);});}
  function sameBaseReadings(records,selected){if(!selected)return[];return(records||[]).filter(row=>row.language===selected.language&&row.base===selected.base&&row.key!==selected.key).sort((a,b)=>b.lastActivityAt-a.lastActivityAt||a.reading.localeCompare(b.reading));}
  function relatedForms(records,selected,limit=12){if(!selected)return[];const chars=new Set(graphemes(selected.base).filter(ch=>/[\p{L}\p{N}\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(ch)));if(!chars.size)return[];return(records||[]).filter(row=>{if(row.key===selected.key||row.language!==selected.language||row.base===selected.base)return false;return graphemes(row.base).some(ch=>chars.has(ch));}).sort((a,b)=>{const A=a.base.includes(selected.base)||selected.base.includes(a.base)?1:0;const B=b.base.includes(selected.base)||selected.base.includes(b.base)?1:0;return B-A||b.lastActivityAt-a.lastActivityAt||a.base.localeCompare(b.base);}).slice(0,limit);}
  function stats(records){const rows=records||[];const languages=new Set(rows.map(x=>x.language).filter(Boolean));return{entries:rows.length,languages:languages.size,observations:rows.reduce((n,x)=>n+(x.observationCount||0),0),retrievals:rows.reduce((n,x)=>n+(x.retrievalCount||0),0),historicalOnly:rows.filter(x=>x.historicalOnly).length};}
  return{norm,graphemes,pitchVariant,pitchKey,pitchLabel,aggregate,search,sameBaseReadings,relatedForms,stats};
});
